/// <reference path=".astro/types.d.ts" />
/// <reference types="astro/client" />
/// <reference types="@cloudflare/workers-types" />
/// <reference path="./worker-configuration.d.ts" />

// Secrets are intentionally not present in wrangler.jsonc. The non-secret
// bindings are generated by `bunx wrangler types` from that config.
declare namespace Cloudflare {
  interface Env {
    CACHE: KVNamespace;
    DB: D1Database;
    INGEST_QUEUE: Queue;
    ASSETS: Fetcher;
    GEMINI_MODEL: 'gemini-3.6-flash';
    FOOTBALL_NEWS_AGENT: DurableObjectNamespace<import('./worker/entrypoint').FootballNewsAgent>;
    GEMINI_API_KEY: string;
  }
}

type Runtime = import('@astrojs/cloudflare').Runtime;

declare namespace App {
  interface Locals extends Runtime {}
}
